# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WinGui_PySide.ui'
#
# Created: Mon Nov 13 18:00:30 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(935, 635)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 30, 401, 211))
        self.groupBox.setObjectName("groupBox")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_10.setLineWidth(0)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(110, 20, 91, 21))
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_11.setLineWidth(0)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(200, 20, 91, 21))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_12.setLineWidth(0)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(290, 20, 91, 21))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_13.setLineWidth(0)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.QSFP1_AR1_LS_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR1_LS_label.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.QSFP1_AR1_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR1_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR1_LS_label.setObjectName("QSFP1_AR1_LS_label")
        self.QSFP1_AR1_EM_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR1_EM_label.setGeometry(QtCore.QRect(20, 80, 91, 41))
        self.QSFP1_AR1_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR1_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR1_EM_label.setObjectName("QSFP1_AR1_EM_label")
        self.QSFP1_AR1_BR_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR1_BR_label.setGeometry(QtCore.QRect(20, 120, 91, 41))
        self.QSFP1_AR1_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR1_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR1_BR_label.setObjectName("QSFP1_AR1_BR_label")
        self.QSFP1_AR1_PF_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR1_PF_label.setGeometry(QtCore.QRect(20, 160, 91, 41))
        self.QSFP1_AR1_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR1_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR1_PF_label.setObjectName("QSFP1_AR1_PF_label")
        self.QSFP1_AR2_LS_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR2_LS_label.setGeometry(QtCore.QRect(110, 40, 91, 41))
        self.QSFP1_AR2_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR2_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR2_LS_label.setObjectName("QSFP1_AR2_LS_label")
        self.QSFP1_AR2_PF_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR2_PF_label.setGeometry(QtCore.QRect(110, 160, 91, 41))
        self.QSFP1_AR2_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR2_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR2_PF_label.setObjectName("QSFP1_AR2_PF_label")
        self.QSFP1_AR2_EM_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR2_EM_label.setGeometry(QtCore.QRect(110, 80, 91, 41))
        self.QSFP1_AR2_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR2_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR2_EM_label.setObjectName("QSFP1_AR2_EM_label")
        self.QSFP1_AR2_BR_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR2_BR_label.setGeometry(QtCore.QRect(110, 120, 91, 41))
        self.QSFP1_AR2_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR2_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR2_BR_label.setObjectName("QSFP1_AR2_BR_label")
        self.QSFP1_AR3_LS_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR3_LS_label.setGeometry(QtCore.QRect(200, 40, 91, 41))
        self.QSFP1_AR3_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR3_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR3_LS_label.setObjectName("QSFP1_AR3_LS_label")
        self.QSFP1_AR3_PF_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR3_PF_label.setGeometry(QtCore.QRect(200, 160, 91, 41))
        self.QSFP1_AR3_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR3_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR3_PF_label.setObjectName("QSFP1_AR3_PF_label")
        self.QSFP1_AR3_EM_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR3_EM_label.setGeometry(QtCore.QRect(200, 80, 91, 41))
        self.QSFP1_AR3_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR3_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR3_EM_label.setObjectName("QSFP1_AR3_EM_label")
        self.QSFP1_AR3_BR_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR3_BR_label.setGeometry(QtCore.QRect(200, 120, 91, 41))
        self.QSFP1_AR3_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR3_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR3_BR_label.setObjectName("QSFP1_AR3_BR_label")
        self.QSFP1_AR4_LS_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR4_LS_label.setGeometry(QtCore.QRect(290, 40, 91, 41))
        self.QSFP1_AR4_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR4_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR4_LS_label.setObjectName("QSFP1_AR4_LS_label")
        self.QSFP1_AR4_PF_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR4_PF_label.setGeometry(QtCore.QRect(290, 160, 91, 41))
        self.QSFP1_AR4_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR4_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR4_PF_label.setObjectName("QSFP1_AR4_PF_label")
        self.QSFP1_AR4_EM_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR4_EM_label.setGeometry(QtCore.QRect(290, 80, 91, 41))
        self.QSFP1_AR4_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR4_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR4_EM_label.setObjectName("QSFP1_AR4_EM_label")
        self.QSFP1_AR4_BR_label = QtGui.QLabel(self.groupBox)
        self.QSFP1_AR4_BR_label.setGeometry(QtCore.QRect(290, 120, 91, 41))
        self.QSFP1_AR4_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP1_AR4_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP1_AR4_BR_label.setObjectName("QSFP1_AR4_BR_label")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(130, 280, 131, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.SFP1_AR_BR_label = QtGui.QLabel(self.groupBox_3)
        self.SFP1_AR_BR_label.setGeometry(QtCore.QRect(20, 120, 91, 41))
        self.SFP1_AR_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP1_AR_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP1_AR_BR_label.setObjectName("SFP1_AR_BR_label")
        self.SFP1_AR_EM_label = QtGui.QLabel(self.groupBox_3)
        self.SFP1_AR_EM_label.setGeometry(QtCore.QRect(20, 80, 91, 41))
        self.SFP1_AR_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP1_AR_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP1_AR_EM_label.setObjectName("SFP1_AR_EM_label")
        self.SFP1_AR_PF_label = QtGui.QLabel(self.groupBox_3)
        self.SFP1_AR_PF_label.setGeometry(QtCore.QRect(20, 160, 91, 41))
        self.SFP1_AR_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP1_AR_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP1_AR_PF_label.setObjectName("SFP1_AR_PF_label")
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_14.setLineWidth(0)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.SFP1_AR_LS_label = QtGui.QLabel(self.groupBox_3)
        self.SFP1_AR_LS_label.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.SFP1_AR_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP1_AR_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP1_AR_LS_label.setObjectName("SFP1_AR_LS_label")
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 280, 131, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.SFP2_AR_LS_label = QtGui.QLabel(self.groupBox_4)
        self.SFP2_AR_LS_label.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.SFP2_AR_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP2_AR_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP2_AR_LS_label.setObjectName("SFP2_AR_LS_label")
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_15.setLineWidth(0)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.SFP2_AR_PF_label = QtGui.QLabel(self.groupBox_4)
        self.SFP2_AR_PF_label.setGeometry(QtCore.QRect(20, 160, 91, 41))
        self.SFP2_AR_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP2_AR_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP2_AR_PF_label.setObjectName("SFP2_AR_PF_label")
        self.SFP2_AR_BR_label = QtGui.QLabel(self.groupBox_4)
        self.SFP2_AR_BR_label.setGeometry(QtCore.QRect(20, 120, 91, 41))
        self.SFP2_AR_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP2_AR_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP2_AR_BR_label.setObjectName("SFP2_AR_BR_label")
        self.SFP2_AR_EM_label = QtGui.QLabel(self.groupBox_4)
        self.SFP2_AR_EM_label.setGeometry(QtCore.QRect(20, 80, 91, 41))
        self.SFP2_AR_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP2_AR_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP2_AR_EM_label.setObjectName("SFP2_AR_EM_label")
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(540, 280, 131, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.SFP3_AR_EM_label = QtGui.QLabel(self.groupBox_5)
        self.SFP3_AR_EM_label.setGeometry(QtCore.QRect(20, 80, 91, 41))
        self.SFP3_AR_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP3_AR_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP3_AR_EM_label.setObjectName("SFP3_AR_EM_label")
        self.SFP3_AR_BR_label = QtGui.QLabel(self.groupBox_5)
        self.SFP3_AR_BR_label.setGeometry(QtCore.QRect(20, 120, 91, 41))
        self.SFP3_AR_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP3_AR_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP3_AR_BR_label.setObjectName("SFP3_AR_BR_label")
        self.SFP3_AR_PF_label = QtGui.QLabel(self.groupBox_5)
        self.SFP3_AR_PF_label.setGeometry(QtCore.QRect(20, 160, 91, 41))
        self.SFP3_AR_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP3_AR_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP3_AR_PF_label.setObjectName("SFP3_AR_PF_label")
        self.SFP3_AR_LS_label = QtGui.QLabel(self.groupBox_5)
        self.SFP3_AR_LS_label.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.SFP3_AR_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP3_AR_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP3_AR_LS_label.setObjectName("SFP3_AR_LS_label")
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_16.setLineWidth(0)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(750, 280, 131, 211))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.SFP4_AR_EM_label = QtGui.QLabel(self.groupBox_6)
        self.SFP4_AR_EM_label.setGeometry(QtCore.QRect(20, 80, 91, 41))
        self.SFP4_AR_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP4_AR_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP4_AR_EM_label.setObjectName("SFP4_AR_EM_label")
        self.SFP4_AR_LS_label = QtGui.QLabel(self.groupBox_6)
        self.SFP4_AR_LS_label.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.SFP4_AR_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP4_AR_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP4_AR_LS_label.setObjectName("SFP4_AR_LS_label")
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_17.setLineWidth(0)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.SFP4_AR_BR_label = QtGui.QLabel(self.groupBox_6)
        self.SFP4_AR_BR_label.setGeometry(QtCore.QRect(20, 120, 91, 41))
        self.SFP4_AR_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP4_AR_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP4_AR_BR_label.setObjectName("SFP4_AR_BR_label")
        self.SFP4_AR_PF_label = QtGui.QLabel(self.groupBox_6)
        self.SFP4_AR_PF_label.setGeometry(QtCore.QRect(20, 160, 91, 41))
        self.SFP4_AR_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SFP4_AR_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SFP4_AR_PF_label.setObjectName("SFP4_AR_PF_label")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 210, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 460, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 71, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 410, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 360, 71, 21))
        self.label_8.setObjectName("label_8")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 520, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 570, 111, 20))
        self.label_9.setObjectName("label_9")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 30, 401, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAutoFillBackground(False)
        self.label_30.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_30.setLineWidth(0)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(110, 20, 91, 21))
        self.label_31.setAutoFillBackground(False)
        self.label_31.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_31.setLineWidth(0)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(200, 20, 91, 21))
        self.label_32.setAutoFillBackground(False)
        self.label_32.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_32.setLineWidth(0)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(290, 20, 91, 21))
        self.label_33.setAutoFillBackground(False)
        self.label_33.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.label_33.setLineWidth(0)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.QSFP2_AR1_LS_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR1_LS_label.setGeometry(QtCore.QRect(20, 40, 91, 41))
        self.QSFP2_AR1_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR1_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR1_LS_label.setObjectName("QSFP2_AR1_LS_label")
        self.QSFP2_AR1_EM_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR1_EM_label.setGeometry(QtCore.QRect(20, 80, 91, 41))
        self.QSFP2_AR1_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR1_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR1_EM_label.setObjectName("QSFP2_AR1_EM_label")
        self.QSFP2_AR1_BR_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR1_BR_label.setGeometry(QtCore.QRect(20, 120, 91, 41))
        self.QSFP2_AR1_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR1_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR1_BR_label.setObjectName("QSFP2_AR1_BR_label")
        self.QSFP2_AR1_PF_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR1_PF_label.setGeometry(QtCore.QRect(20, 160, 91, 41))
        self.QSFP2_AR1_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR1_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR1_PF_label.setObjectName("QSFP2_AR1_PF_label")
        self.QSFP2_AR2_LS_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR2_LS_label.setGeometry(QtCore.QRect(110, 40, 91, 41))
        self.QSFP2_AR2_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR2_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR2_LS_label.setObjectName("QSFP2_AR2_LS_label")
        self.QSFP2_AR2_PF_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR2_PF_label.setGeometry(QtCore.QRect(110, 160, 91, 41))
        self.QSFP2_AR2_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR2_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR2_PF_label.setObjectName("QSFP2_AR2_PF_label")
        self.QSFP2_AR2_EM_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR2_EM_label.setGeometry(QtCore.QRect(110, 80, 91, 41))
        self.QSFP2_AR2_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR2_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR2_EM_label.setObjectName("QSFP2_AR2_EM_label")
        self.QSFP2_AR2_BR_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR2_BR_label.setGeometry(QtCore.QRect(110, 120, 91, 41))
        self.QSFP2_AR2_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR2_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR2_BR_label.setObjectName("QSFP2_AR2_BR_label")
        self.QSFP2_AR3_LS_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR3_LS_label.setGeometry(QtCore.QRect(200, 40, 91, 41))
        self.QSFP2_AR3_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR3_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR3_LS_label.setObjectName("QSFP2_AR3_LS_label")
        self.QSFP2_AR3_PF_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR3_PF_label.setGeometry(QtCore.QRect(200, 160, 91, 41))
        self.QSFP2_AR3_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR3_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR3_PF_label.setObjectName("QSFP2_AR3_PF_label")
        self.QSFP2_AR3_EM_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR3_EM_label.setGeometry(QtCore.QRect(200, 80, 91, 41))
        self.QSFP2_AR3_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR3_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR3_EM_label.setObjectName("QSFP2_AR3_EM_label")
        self.QSFP2_AR3_BR_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR3_BR_label.setGeometry(QtCore.QRect(200, 120, 91, 41))
        self.QSFP2_AR3_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR3_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR3_BR_label.setObjectName("QSFP2_AR3_BR_label")
        self.QSFP2_AR4_LS_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR4_LS_label.setGeometry(QtCore.QRect(290, 40, 91, 41))
        self.QSFP2_AR4_LS_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR4_LS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR4_LS_label.setObjectName("QSFP2_AR4_LS_label")
        self.QSFP2_AR4_PF_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR4_PF_label.setGeometry(QtCore.QRect(290, 160, 91, 41))
        self.QSFP2_AR4_PF_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR4_PF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR4_PF_label.setObjectName("QSFP2_AR4_PF_label")
        self.QSFP2_AR4_EM_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR4_EM_label.setGeometry(QtCore.QRect(290, 80, 91, 41))
        self.QSFP2_AR4_EM_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR4_EM_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR4_EM_label.setObjectName("QSFP2_AR4_EM_label")
        self.QSFP2_AR4_BR_label = QtGui.QLabel(self.groupBox_2)
        self.QSFP2_AR4_BR_label.setGeometry(QtCore.QRect(290, 120, 91, 41))
        self.QSFP2_AR4_BR_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.QSFP2_AR4_BR_label.setAlignment(QtCore.Qt.AlignCenter)
        self.QSFP2_AR4_BR_label.setObjectName("QSFP2_AR4_BR_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 23))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuOptions.addAction(self.actionLoad)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionExit)
        self.menuOptions.addSeparator()
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Credo QSFP-SFP Tester", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "QSFP1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "AR1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "AR2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "AR3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "AR4", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR1_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR1_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR1_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR1_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR2_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR2_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR2_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR2_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR3_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR3_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR3_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR3_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR4_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR4_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR4_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP1_AR4_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "SFP1", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP1_AR_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP1_AR_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP1_AR_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "AR1", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP1_AR_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "SFP2", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP2_AR_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "AR2", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP2_AR_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP2_AR_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP2_AR_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "SFP3", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP3_AR_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP3_AR_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP3_AR_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP3_AR_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "AR3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "SFP4", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP4_AR_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP4_AR_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "AR4", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP4_AR_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.SFP4_AR_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Link Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Eye Margin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "BER", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Pass/Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Pass/Fail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Link Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "BER", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Eye Margin", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Reset All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "QSFP2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "AR1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "AR2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "AR3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "AR4", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR1_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR1_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR1_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR1_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR2_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR2_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR2_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR2_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR3_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR3_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR3_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR3_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR4_LS_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR4_PF_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR4_EM_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.QSFP2_AR4_BR_label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load Alterate Script", None, QtGui.QApplication.UnicodeUTF8))

